import { Test, TestingModule } from '@nestjs/testing';
import { AppController } from './app.controller';
import { AppService } from './app.service';

describe('AppController', () => {
  let appController: AppController;

  beforeEach(async () => {
    const app: TestingModule = await Test.createTestingModule({
      controllers: [AppController],
      providers: [AppService],
    }).compile();

    appController = app.get<AppController>(AppController);
  });

  describe('App Controller (e2e)', () => {
    it('/restaurants/227018 (GET)', async () => {
      const response = await appController.getRestaurant('227018');

      const expectedResponseBody = {
        name: 'Ekkamai Macchiato - Home Brewer',
        id: '227018',
        coverImage:
          'https://img.wongnai.com/p/1920x0/2021/03/09/fc6f2b50e313418590eb113cbc4981c2.jpg',
        menus: [
          'Promotion A หมูสามชั้นคั่วพริกกระเทียมไข่ดาว',
          'Promotion B กะเพราหมูสับ ไข่ดาว',
          'Promotion C กะเพราเนื้อสับ ไข่ดาว',
          'Promotion D ข้าวหมูกระเทียมไข่ดาว',
          'Set A กะเพราหมูสับไข่ดาว + กาแฟ',
          'Set B หมูกระเทียมไข่ดาว + กาแฟ',
          'Set C หมูสามชั้นคั่วพริกกระเทียม ไข่ดาว + กาแฟ',
          'Set D หมูผัดไข่ + กาแฟ',
          'Set E กะเพราเนื้อสับไข่ดาว + กาแฟ',
          'Set H ข้าวผัดปู + กาแฟ',
          'Set J ข้าวไข่ขยี้ปู + กาแฟ',
          'Set K ข้าวคอหมูทอดน้ำปลา + กาแฟ',
          'Set M หมูกรอบผัดพริก ไข่ออนเซ็น + เครื่องดื่ม',
          'Set N สามชั้นคั่วพริกกระเทียม ไข่ดาว + Choux Cream',
          'Set O กะเพราหมูสับไข่ดาว + Choux Cream',
          'Set P Choux Cream + เครื่องดื่ม',
          'Duo A กะเพราหมูสับไข่ดาว + หมูกระเทียมไข่ดาว',
          'Duo B หมูสามชั้นคั่วพริกกระเทียมไข่ดาว + กะเพราหมูสับไข่ดาว',
          'Duo D หมูสามชั้นคั่วพริกกระเทียม 2 จาน',
          'อะไรก็ได้ ง่ายๆ',
          'Iced Caffe Latte',
          'Iced Americano',
          'Iced Caramel Macchiato',
          'Iced Caffe Mocha',
          'Hot Caffe Latte',
          'Hot Americano',
          'Hot Caramel Macchiato',
          'Hot Caffe Mocha',
          'Hot Cappuccino',
          'Piccolo Latte',
          'Dirty',
          'Cold Brew Botton',
          'Drip Colombia El Paraiso Sakura',
          'Drip Ethiopia Guji',
          'Amber Hive',
          'Guilty Pleasure',
          'Chai',
          'Espresso x Orange',
          'Miyazaki',
          'Honey Bee',
          'Rest in Peach',
          'Coffee Jelly',
          'Frozen Lemonade Espresso',
          'Lychee and Rose Tea',
          'Peach Tea',
          'Oriental',
          'Yuzu Soda ยูสุ โซดา',
          'Yuzu Float',
          'Orange Tonic',
          'Yuzu Fizz',
          'Thai Milk Tea Float',
          'Thai Milk Tea',
          'Orange Juice',
          'Heartbeat',
          'Bunny',
          'Water',
          'Sparkling',
          'นมร้อน',
          'Iced Lemonade',
          'Hot Chocolate',
          'Iced Chocolate',
          'Iced Matcha Latte',
          'Hot Matcha Latte',
          'กะเพราหมูสับ Pork with Holy Basil',
          'กะเพราหมูตุ๋น Stewed Pork with Holy Basil',
          'หมูกระเทียม Pork with Garlic',
          'หมูสับพริกแห้งโหระพา Spicy Pork with Sweet Basil',
          'หมูกรอบผัดพริก Spicy Crispy Pork',
          'หมูกรอบหม่าล่า Spicy Crispy Pork with Mala',
          'หมูกรอบคั่วไข่ Crispy Pork with Egg',
          'ข้าวผัดหมูกรอบ Spicy Fried Rice with Crispy Pork',
          'หมูมิโสะ Miso Pork',
          'แกงกะหรี่หมู Pork Curry',
          'Green Pork Curry แกงเขียวหวานหมู',
          'ซี่โครงหมูน้ำผึ้ง Honey Ribs',
          'ข้าวผัดเบคอน Fried Rice with Bacon',
          'สุกี้แห้งหมู Thai Style Pork Sukuyaki',
          'คอหมูทอดน้ำปลา Deep Fried Pork Jowl',
          'หมูสามชั้นคั่วพริกกระเทียม Spicy Pork Belly',
          'Egg',
          'ข้าว',
          'กะเพราเนื้อสับ Beef with Holy Basil',
          'กะเพราเนื้อตุ๋น Stewed Beef with Holy Basil',
          'เนื้อกระเทียม Beef with Garlic',
          'เนื้อพริกแห้ง โหระพา Spicy Beef with Sweet Basil',
          'ริบอายเผ็ด Spicy Rib Eye Rice Bowl',
          'เนื้อสันนอกย่าง Pan Seared Striploin',
          'ข้าวผัดมันเนื้อ Spicy Fried Rice with Beef Fat',
          'เนื้อมิโสะ Miso Beef',
          'แกงกะหรี่เนื้อ Beef Curry',
          'สุกี้แห้งเนื้อ',
          'สตูว์เนื้อ Beef Stewed',
          'กุ้งกระเทียม Shrimp with Garlic',
          'กุ้งกะเพรา Shrimp with Holy Basil',
          'กุ้งคั่วพริกกระเทียม Spicy Shrimp',
          'กุ้งซอสโหระพา Shrimp with Sweet Basil Sauce',
          'ปูผัดพริก Spicy Crab Meat',
          'ข้าวผัดปู Fried Rice with Crab Meat',
          'ปูผัดพริกเหลือง Crab Meat with Yellow Chili',
          'ปูไข่ขยี้ Crab Meat with Egg',
          'ข้าวแซลม่อนทอดน้ำปลา Deep Fried Salmon with Fish Sauce',
          'ข้าวแซลม่อนคั่วพริกกระเทียม Spicy Salmon',
          'ข้าวแซลมอนเทอริยากิ Salmon Teriyaki',
          'ข้าวแซลม่อนซอสโหระพา Salmon with Sweet Basil Sauce',
          'สปาเก็ตตี้เบคอนพริกแห้ง Garlic and Bacon Spaghetti',
          'สปาเก็ตตี้ซอสมะเขือเทศเบคอน Tomato Bacon Spaghetti',
          'สปาเก็ตตี้กุ้งคั่วพริกกระเทียม Spicy Shrimp Spaghetti',
          'สปาเก็ตตี้กุ้งซอสมะเขือเทศพริกแห้ง Tomato Shrimp Spaghetti',
          'สปาเก็ตตี้กุ้งซอสโหระพา Shrimp Sweet Basil Spaghetti',
          'สปาเก็ตตี้ปูคั่วพริกกระเทียม Spicy Crab Meat Spaghetti',
          'สปาเก็ตตี้ปูซอสโหระพา Crab Meat with Sweet Basil Spaghetti',
          'สปาเก็ตตี้แซลมอนซอสโหระพา Salmon Sweet Basil Spaghetti',
          'กะเพราเห็ด Shimeji Holy Basil',
          'เต้าหู้ เห็ด กระเทียม Tofu Shimeji Garlic',
          'เต้าหู้เห็ด ซอสโหระพา Tofu Shimeji Sweet Basil',
          'เต้าหู้ เห็ด คั่วพริกกระเทียม Spicy Shimeji',
          'เต้าหู้ เห็ด พริกแห้งโหระพา Tofu Shimeji Sweet Basil',
          'สปาเก็ตตี้เห็ด ซอสมะเขือเทศ Tomato Shimeji Spaghetti',
          'สปาเก็ตตี้เห็ด ซอสโหระพา Shimeji Sweet Basil Spaghetti',
          'สุกี้แห้ง เต้าหู้ เห็ด Tofu Shimeji Sukiyaki',
          'Peach Vodka Soju Ice Cream',
          'Ice Cream Chocolate Caramel',
          'Chocolate cookie',
          'Lotus Biscoff',
          'Choux Cream',
          'Blueberry Cheese Pie',
          'Coconut Cake Box',
          'BANOFFEE box',
          'Baileys Irish Cream Tiramisu',
          'Banana Cake',
          'Toffee cake delivery ( อุ่น 20 วินาที )',
          'Mixed Berry Cheese Pie',
          'Shine Muscat Cheese Pie',
          'Carrot Cake',
          'Salted Caramel Chocolate Tart',
          'Basque Cheese Cake',
          'Dark Beer Chocolate Cake',
          'Caramel Macadamia Cake',
          'Ice Cream Thai Tea',
          'Honey Lemon Cake',
          'Nutella Cake',
          'Strawberry Custard cake',
          'Yuzu Cake',
          'Strawberry Cheese Pie',
          'Black Forest box',
          'Peach and Blueberry Crumble Cheesecake',
          'Bailey’s Strawberry Shortcake',
          'Durian Cheese Pie',
          'Coconut Cake',
          'Durian Cheese Cake',
          'Coconut Mini Box',
          'Japanese Sweet Potato Choux Cream',
          'Banoffe Cake',
          'Black Forest Cake',
          'Blueberry Cheese Cake',
          'Croissant',
          'Caramel Custard Cake',
          'Chocolate Caramel Pistachio and Almond Cake',
          'Chocolate Cherry',
          'Chocolate Mixed Berries',
          'Fig and Almond Tart',
          'Japanese Pumpkin Cheesecake',
          'Japanese Sweet Potato Cheese Cake',
          'Lychee and Rose Cake',
          'Mango Cheese Cake',
          'Matcha Cheese Cake',
          'Matcha and Japanese Sweet Potato',
          'Muscat Almond Tart',
          'Peach and Strawberry Cheese cake',
          'Strawberry Fresh cream cake',
          'Strawberry cheese cake 🍓',
          'Sweet Potato and pumpkin cheesecake',
          'White Chocolate Raspberry Tart',
          'Cheese Cake with Caramel Macadamia',
          'Chocolate Mixed Berry Cheese Cake',
          'Barque Durian Cheese Cake',
          'Durian Cheese Cake Box',
          'Marian Plum Cheese Cake',
          'มะยงชิดเค้ก',
          'Durian Cheese cake no bake',
          'Set B ข้าวหมูกระเทียมไข่ดาว + เครื่องดื่ม',
          'Set C ข้าวหมูสามชั้นคั่วพริกกระเทียม + เครื่องดื่ม',
          'Set Dข้าวหมูผัดไข่ + เครื่องดื่ม',
          'Set Eข้าวกะเพราเนื้อสับไข่ดาว + เครื่องดื่ม',
          'Set F ข้าวคอหมูทอดกระเทียม + เครื่องดื่ม',
          'Set G ข้าวหน้าไก่ย่าง + เครื่องดื่ม',
          'Set H ข้าวผัดปู + เครื่องดื่ม',
          'Set L ข้าวหมูสามชั้นย่างซอสโคชูจัง ไข่ออนเซ็น + เครื่องดื่ม',
          'Set M ข้าวหมูกรอบผัดพริก ไข่ออนเซ็น + เครื่องดื่ม',
          'Set N ข้าวหมูสามชั้นคั่วพริกกระเทียม ไข่ดาว + Vanilla Choux Cream',
          'Set O ข้าวกะเพราหมูสับไข่ดาว + Vanilla Choux Cream',
          'Set P Vanilla Choux Cream + เครื่องดื่ม',
          'Set Q ข้าวหมูสามชั้นคั่วพริกกระเทียมไข่ดาว+Japanese Potato Choux Cream',
          'Set S Japanese Potato Choux Cream + เครื่องดื่ม',
          'Duo 1 ข้าวกะเพราหมูสับไข่ดาว + หมูกระเทียมไข่ดาว',
          'Duo 2 ข้าวหมูสามชั้นคั่วพริกกระเทียมไข่ดาว + กะเพราหมูสับไข่ดาว',
          'Duo 3 ข้าวหมูสามชั้นคั่วพริกกระเทียมไข่ดาว + ข้าวหมูผัดไข่',
          'Duo 4 ข้าวหมูสามชั้นคั่วพริกกระเทียมไข่ดาว สองที่',
          'ซื้อ 2 แถม 1 เครื่องดื่ม',
        ],
        activeTimePeriod: { open: '08:00', close: '17:00' },
      };

      expect(response).toEqual(expectedResponseBody);
    });
  });
});
